name: daily-downloads-to-bq

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # JST 11:00

jobs:
  android:
    runs-on: [self-hosted]   # ← Macのrunnerに投げる
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install

      - name: Android latest (pubsite -> BQ)
        env:
          BQ_PROJECT: store-kpi
          BQ_DATASET: app_kpi_raw
          BQ_TABLE_DAILY: downloads_daily
          BQ_LOCATION: US

          # pubsite
          GCS_BUCKET: pubsite_prod_rev_02126004667937646089
          GCS_PREFIX: stats/installs/installs_jp.baibai.fbingo_
        run: npm run run:android:latest

  ios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      - name: iOS latest (ASC -> BQ)
        env:
          BQ_PROJECT: store-kpi
          BQ_DATASET: app_kpi_raw
          BQ_TABLE_DAILY: downloads_daily
          BQ_LOCATION: US
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_PRIVATE_KEY: ${{ secrets.ASC_PRIVATE_KEY }}
          ASC_VENDOR_NUMBER: ${{ secrets.ASC_VENDOR_NUMBER }}
        run: npm run run:ios:latest
